@jwt_token = {{sessions.response.body.token}}

# @name users
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafael@email.com",
  "password": "123456"
}

# @name sessions
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "user.adm@email.com",
  "password": "admin123321"
}

# @name technicians
GET http://localhost:3333/technicians
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/technicians
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Rafael",
  "email": "rafael.tech@email.com",
  "password": "123456",
  "timeIds": []
}

PUT http://localhost:3333/technicians/56db04e8-3114-4bf9-ab66-fdb265df095b
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Gabriel",
  "email": "gabriel@tech.com",
  "timeIds": [13, 14, 15, 16, 17]
}

# @name Services
GET http://localhost:3333/services
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/services
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Instalação de Rede",
  "price": 100
}

PUT http://localhost:3333/services/d4c0b1ef-24b0-4a51-935c-f9e04aa84778
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Recuperação de Dados",
  "price": 200
}

PATCH http://localhost:3333/services/d4c0b1ef-24b0-4a51-935c-f9e04aa84778
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "status": "ativo"
}

# @name Customers
GET http://localhost:3333/customers
Authorization: Bearer {{jwt_token}}

PUT http://localhost:3333/customers/81d719d1-553b-4b09-aa64-a7d2ca6d7a72
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "José",
  "email": "jose@client.com"
}