@jwt_token = {{sessions.response.body.token}}

################################################

# @name users
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Miguel",
  "email": "miguel@email.com",
  "password": "123456"
}

################################################

# @name sessions
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "gabriel@tech.com",
  "password": "#técnicogabriel123"
}

################################################

# @name times
GET http://localhost:3333/times
Authorization: Bearer {{jwt_token}}

################################################

# @name technicians
GET http://localhost:3333/technicians
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/technicians
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Elisangela",
  "email": "eli@tech.com",
  "password": "123123",
  "timeIds": []
}

PUT http://localhost:3333/technicians/a29309e0-4423-49dd-b21e-a5a8f64c5932
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Elisangela",
  "email": "elisangela@tech.com",
  "timeIds": [1, 2, 3, 4, 4, 5, 5, 6]
}

################################################

# @name Services
GET http://localhost:3333/services
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/services
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Instalação de Rede",
  "price": 100
}

PUT http://localhost:3333/services/d4c0b1ef-24b0-4a51-935c-f9e04aa84778
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Recuperação de Dados",
  "price": 200
}

PATCH http://localhost:3333/services/d4c0b1ef-24b0-4a51-935c-f9e04aa84778
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "status": "ativo"
}

################################################

# @name Customers
GET http://localhost:3333/customers
Authorization: Bearer {{jwt_token}}

PUT http://localhost:3333/customers/136e15fa-90cd-45e9-b38c-6f690c6b91fc
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Claúdio",
  "email": "claudio@client.com"
}

DELETE http://localhost:3333/customers/90fabf1f-50af-41bd-8110-3603115207ad
Authorization: Bearer {{jwt_token}}

################################################
# @name Tickets
GET http://localhost:3333/tickets
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/tickets
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Instalação de Rede",
  "description": "Instalação de rede via cabo",
  "serviceId": "f781e233-10df-42ab-9489-2bd626324e8b"
}

PATCH http://localhost:3333/tickets/7711be7f-636e-4915-a2f5-9871815cbf7a/status
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "status": "encerrado"
}