@jwt_token = {{sessions.response.body.token}}

# @name users
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafael@email.com",
  "password": "123456"
}

# @name sessions
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "user.adm@email.com",
  "password": "admin123321"
}

# @name technicians
GET http://localhost:3333/technicians
Authorization: Bearer {{jwt_token}}

POST http://localhost:3333/technicians
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Rafael",
  "email": "rafael.tech@email.com",
  "password": "123456",
  "timeIds": [1, 2, 3, 4, 5, 8, 9, 10, 11, 12]
}

PUT http://localhost:3333/technicians/3a2b8b79-d615-4085-be80-76e81f0a7173
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "timeIds": [1, 2, 3, 4, 5, 6, 7]
}

# @name Services
POST http://localhost:3333/services
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "Instalação de Rede",
  "price": 100
}
